language: scala
jdk:
- oraclejdk8
before_install:
- export PATH=${PATH}:./vendor/bundle
- openssl aes-256-cbc -K $encrypted_685c161ef15d_key -iv $encrypted_685c161ef15d_iv -in secring.asc.enc -out secring.asc -d
script:
- scripts/travis-publish.sh
install:
- pip install --user codecov
- gem install jekyll -v 2.5

jobs:
  include:

    - stage: test
      script: sbt test
    - stage: test
      script: sbt docs/makeMicrosite

    - stage: deploy
      if: (branch = master)
      script:
        - sbt publishSigned sonatypeRelease
        - sbt docs/publishMicrosite

notifications:
  webhooks:
    urls:
      - "${GITTER_WEBHOOK_URL}"
    on_success: change
    on_failure: always
    on_start: false
env:
  global:
  # GITHUB_TOKEN
  - secure: GofXtV7F4zU9SD041QiugjlA+ezjIEcO1g+vcPPeRTCZRswdiBfLBqtv5CZ/QGRyN3ti116aKJNFSiqhLrefwPdfmOvvih0CI/Qw+yrTPp+wobj0c5KHf9eHPYgQBnv8btNa2BPTt/++W29PHA5hpBN+LmdTg+5Su5geouqw1MMhlerZxJU8gSZAOCwWvK5/x6BEjCHX7LComxfH7D9OCtNbcKd2JGAIzk7Dowx8wgYwla6AK4/R4ixrAlXrrIKa3SWWqOZ7q8efGfdyI05e00f+Vuy83Z1GcNZPJoucJxPEaV2g89beCwaXnfzdK0AcL8I0tYIVHWDOyfGLw2sr5Sg0AFbRwKDhZreKmaBNiD9aduJyRxvAPAt+nIKMig0ZM8/OqQRRwPmtV0Q4OKqbxprR0yFcqom6nUGXLPGSYapM5Av7JEDo4DQssOB4G9BQZ8rfYIC2AdTJgtlvhDBSZDycKeunjpPywf1m0GiKsVHu1DicGn7W9qUSKeVaw7rRqoPUIgvdqlTcPP5DyGGeynlR3r7x1bRGxRL7OFX1p5KHokwfSdoVHtaQiLSHlRDzipmk90RW7CgBZmmg6kAqhZRtlF+pnScbkR81C0qyKGiCZ1eRekvxsqolvgvIF2E98FzJQM5Tc0uPLxwf3KSy2m1ZZbzQ4ZpKncvA6w7WS0U=
  # SONATYPE_USER
  - secure: b4MsEc6tEY6KZled7G/g5mj/xVNgAhkHh5ea0ukSWQi9nLBnHFwDuH7WGAu4N+VM/c3JS7G+LzjH3E2htMBXj9ApIYFBqohobdeKqgWJC7NzKVAnbDKx5VNShtkmlw4cz7lQLTJWb8SUzho9ebpDe4FSHbV/KlvgiYVTKzp4fBpmE36IvFvj6DAnj14JlXO6+D7JE8U84s5u1Ib4XVTAXgHN1Yrx7oclnKQFY8++VtjMhs8dqR4aV1JX1OS0fAuVqOT9TvwGj3MJbY7xr0DAIU8VpQYd5n9oADWuUrOsVNFGBOeiT9eHq8ubOqeHjRI0Vxsxv5GjD6CjzmaD2yR3DX3+zTcQFdTMN7G0U19iIGJ7ddKxQzv0K4s+h1Yd24ptCQ0Ou4cMCT5Q1hCobglJ+2enGbyM3nW/VEl3ih7ch5sIKHzpBdxxaqTMlqWpD9N1JpAJHxsccGRSXHIFEC/rNCGi1wcUBaH4E8C+KFUuFiDToiJy1+rZHRYGgV5eheDEkmi96kDYysJ3WuBZIU9APQPhMIcu5Bfn0YGCrhncUySZ0lO0LEoLkShlOJbpAMNTFnyKJwxcACQ7LsxbEp+QdjlrTv1+ZZ+vPh+HRvQWjayov+xW00C0EULskytCuulR92By74lxxvSpdKBboqu3WOymySuodv+UYo4qOA3PzO4=
  # SONATYPE_PASSWORD
  - secure: Cbq+PRqOK1fLtgAG0K/8I5TV/tPBxZhrdLzGQU5aXPYTvjZS4p1rqXU4E1goQQMMtUSzzS7AhW/vE8w2ZxeKZTOL82KJ5Ym7eThBxbH34LyJ27aWbttTGW2nooxRr3oKjqHc40SKgd6EK8ojRpFTdSGvnJE9oljnE3Aos1ucu11MqyKXF6jkdHRD54IofT2X014gt2s/+AOBH2gi3PicMXnwb4wcQcMX161lIN22Mb1oAzHJlkg6n2Z/EEF/9DT07qZZD2Ep9aX9Xf64oUa1mK7mePi8u4oAo9jJjDX5cHk1WccwEsDgbSfRLah3dyiIXZavJDplKpt0s4KUtImfw2cJ0I0cXnRIWwWkT7GLZXJhfdlDUBLv07J+HQwGzih0Y3KtNjMcLR2woxTO00mgHlrvFZqCgVofUn5iZG8oOkyl0JQmpFHJAwBtqzIIZ3g/m0ycwgP4hL9Exgm+5jkuD+XdQHvy/uNsfox6XY07vTySe0LRINjWLDwiV/QwTEgFyI/zLvmC5mrikCuUk4RaSwb39YiHvqHRUxn56wgWZUJFTTbPeBQ++D1dSMNH20VljAJJqEzflqJbaQ8q3sqbmHZDNCQc15WyC47SlgItVPvMul+8qxfW2fNDvxBU3t61GaliRfQYyWYV8xT/kiPVC+zRMZz/Iq34rQ1SM2/4aaM=
  # PGP_PASSPHRASE
  - secure: "iyq16vQrLfaDpbvKtvh5EXtNAyWM2gt/xPgxSj8KDnXyb39FIjzi65ogtixjIgAX7zYv/+tqF+C6j/6P5r2hgnxsZGTfPyed/kph+qEm7/jZxbYtzEuKw6EIk+fY67EKPA+o+XiEsK5ZV8o9o3jHJr/bl08bmusJ8Q7dst3LyNwPZ1WUO8++5v8H33cpqh17GwBKDNX5w6q48tsjfZFFRZ7Vh99eSO3IfT78BS5nPSmbCHAE256Esci09HDy4qLd0UwrOQbJLf9WyLxy/oG2qXRns3oEICMleqqlKJQdEV5eHFGnNZjj8qyTM1pPSLEU5MRyr9mWHcuD0ZP8eZM4aUQuRk/Zog7zYZ4d0ScG6wmzciJjX8kzda8ZhobUe1D/wAd3sXdFf7Q4CPQFjHHjWqA2ZqyH7Aqlfv6o+9BorFD+teSAt7yxZjGc36LN2H+GIFRDxBelcgwGLbHH29MGm3xfThNTw74GMwn2FnSmmy/Ryfq/95bF7YFvHLH0brIaAtmWlQ7DoneJyfbfiP9AcXJoJe8To8nuwjNz214UZ+iYO51x+3Br3KkFIB4cR11tBjouV4UrbeiTDexH425KDSI3RFx1fzGDkIPzAF3nK49EHBwQJRB0Oo/cDNrlBh1/KS8Wigeuz8d27LTUk0KSm5h8crR6f7SxaVxKvKhJdfA="
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
  - "$HOME/.coursier"
  - "$HOME/.cache"
