language: scala
jdk:
- oraclejdk8
before_install:
- export PATH=${PATH}:./vendor/bundle
- openssl aes-256-cbc -K $encrypted_685c161ef15d_key -iv $encrypted_685c161ef15d_iv -in secring.asc.enc -out secring.asc -d
script:
- scripts/travis-publish.sh
install:
- pip install --user codecov
- rvm use 2.6.0 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.2.1

jobs:
  include:

    - stage: test
      script: sbt test
    - stage: test
      script: sbt docs/makeMicrosite

    - stage: deploy
      if: (branch = master)
      script:
        - sbt publishSigned sonatypeReleaseAll docs/publishMicrosite

notifications:
  webhooks:
    urls:
      - "${GITTER_WEBHOOK_URL}"
    on_success: change
    on_failure: always
    on_start: false
env:
  global:
  # GITHUB_TOKEN
  - secure: "ru8FS/4GYJLJ+PAXvMybLME9NoFDLpIdXZJHp02pyIvfO2L502/zDf+zdAg4oXLNJmpUaWjzuKGYMYTDFT2J+K+PeFnSTY9mw25blH2aX0PiQEQsArSP3Mh8yacuwD9adSBkZUpKCECvDte5heuFymz2Sl8WVJqmjE7ynKl7rLSBdfRI9lxjUvmGWOAIdFRS0BvrWCVObm45O3DrcQ9JyXJY6dD0L1olQCKicS2gL5ZQfeiGx0HXbsMzp04BBcpET1xnIMlHVt8wyq4lZb1HzOy3sC2XlP2aQw8HP1kZDRG646IPgTuXgT7LlzdXVDOw9b4Nmyl0iwAMRUyi6bPcY+Eyq2ef3nvbFj/mnrkjmXLhgescEffoQ0V/YN3O8oIWilT0ywD3DW2uBB8CSawXhIMZoEeBefOKXo+v8dF4dDLxfekiDKPvYxeGcjXoSs5WhjOFEAqq6ltjhsCoCY9m05Ej0eFmgUsv5hmvm1CmUKjSLmXnUED6MDUpNkBUZDBgyO9aXd6qUlIgO32Iy3PwVcmDCxBwLRHM9W3LfiePnwDZeTeC2hxQWb02znH1QUoQ3MrbqivhQ3inxrOSwVArRkgbnH+X4tzibnkBFWkcmq7a2hQuiWWJ60QKeplLovYJHgl0hSu6mQBHuJKugVLTLlzP04JVz3rpwZAu5pwafmo="
  # SONATYPE_USER
  - secure: "JOLfdgeF20yJT3pDFfJfuJTXVYpnxruO1A1d2zHCVSrmLHhab1osHdS/zpJuL8oXLJojxH95G/faASPRefJGhJ7fLzJPGobP/LvODXwZ0U+fS+LCXEpFKbf1Jsct7qzCT7MjXOZLXb2awfEmj/ft3U6iOATXEd7rTCJnH2nyLDdUVxWcY0DjByeTmkrgHXBl51ysin5/48pnUBXzBb8zMuG634WFe+EqPN58YaVlTAk6idrCkdv6VWx6B0ctl8DGJcz9SYQ1GraaIwK6NytE0YIC+SSn6EaqlYohkLgwj0IpA6iGxjjJSPgq4cLQdI9dymql7133w6d0xKIQ9PhLqawhIZ6bRq29VIW0oRWu4o75YZQFSTOX4QVAbi5BpuQU3ZGDgLqqO9ecdonh5ItLUlbMgjdl3kFuShThX+ANczpnOuRWj3e5gy1z6mondI55OhFrTwfn3A+w8hxqk+TlEBg8r1IN19TXaJoffnrWpOdUXNuO6S/PXiOFQc/2KUMcLuRfprf2H+ANqbp+RdDhOptb3xB87QVr0K2XXPDpxyG5ser8jbU+fA/77aIAJ1Ag+fSXfIkCiLZoCjzzOrrRKV5NyhJf2il7Ml8R4ActSHd2VdDFdfqvdPr/8gVP1IhzS8NnuAtl0MOHz8lUw7EHr9bx+97R++yEavUC/tEstyY="
  # SONATYPE_PASSWORD
  - secure: "oqo/t2HmtTadm0bExeCr2AMZhylsEzh05WKjBhIACYy0hB5e7kPKqWb5IBRLqCdJUfgmW4q5dWyg9TB9aKzQgdXtqrbzV4K8lsDNtOBZJMbeioVaSPMGOi3b6q4y6LHuu2r4utdasFBQRxc4dtneoZpl0TjS7gScCAqIBUUR0N8kAqclZojhGEfBE3ZwqYslJsjT2OXJHjPSlTIef7i1GhXxPzj/TO4rzLNjoNb0eyV4ZPwe5hXJIXEQrvtRsk5w32goVerf3P0v6Mq3f0bX+6kTGaquwJsManJtWZhX6PnS/xAFw9rYJlTkrtDR+iAG7v1F5UThUTUItUfhW44qLlBikp5uAsmasfIyPKeN5AFgPrg79vs6Q4GLC7AZsaGewue85ngVljU9gsPNhXRcgeJGTfQC3B8a4JelGLlTFwjrzwkSs76lcmZoE3Jjw9l4DibUncyrViUV1hkRlF0gV0La7+8PVmx/1CbcLuk6IDHHZanh6FwY9J8Ac4C5zGuese2Zr/jm6mNkRqHVTbwlwRz+J9ptyzc7C9VfH9RA58m5Y/SnYpzxSJjf/mRSinvoHYH/nIyHzhlyR8Z5eVS9J+OZrgh1s3PFQ5rnvdXndU/wxkbnNLNGrdANnvS8gKyEwmIh47E+ctaBQ9dvSZxQNsZt7Yf5q3DuvjNdSwDzwIE="
  # PGP_PASSPHRASE
  - secure: "iyq16vQrLfaDpbvKtvh5EXtNAyWM2gt/xPgxSj8KDnXyb39FIjzi65ogtixjIgAX7zYv/+tqF+C6j/6P5r2hgnxsZGTfPyed/kph+qEm7/jZxbYtzEuKw6EIk+fY67EKPA+o+XiEsK5ZV8o9o3jHJr/bl08bmusJ8Q7dst3LyNwPZ1WUO8++5v8H33cpqh17GwBKDNX5w6q48tsjfZFFRZ7Vh99eSO3IfT78BS5nPSmbCHAE256Esci09HDy4qLd0UwrOQbJLf9WyLxy/oG2qXRns3oEICMleqqlKJQdEV5eHFGnNZjj8qyTM1pPSLEU5MRyr9mWHcuD0ZP8eZM4aUQuRk/Zog7zYZ4d0ScG6wmzciJjX8kzda8ZhobUe1D/wAd3sXdFf7Q4CPQFjHHjWqA2ZqyH7Aqlfv6o+9BorFD+teSAt7yxZjGc36LN2H+GIFRDxBelcgwGLbHH29MGm3xfThNTw74GMwn2FnSmmy/Ryfq/95bF7YFvHLH0brIaAtmWlQ7DoneJyfbfiP9AcXJoJe8To8nuwjNz214UZ+iYO51x+3Br3KkFIB4cR11tBjouV4UrbeiTDexH425KDSI3RFx1fzGDkIPzAF3nK49EHBwQJRB0Oo/cDNrlBh1/KS8Wigeuz8d27LTUk0KSm5h8crR6f7SxaVxKvKhJdfA="
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
  - "$HOME/.coursier"
  - "$HOME/.cache"
