name: TotalMap
baseurl: /total-map
description: Simple library for total maps
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.1+17-e76743b4
org: com.github.krever
markdown: kramdown
