name: TotalMap
baseurl: /total-map
description: Simple library for total maps
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.1+14-c0dad29e
org: com.github.krever
markdown: kramdown
