name: TotalMap
baseurl: /total-map
description: Simple library for total maps
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.1+3-2acb5872
org: com.github.krever.totalmap
markdown: kramdown
